### ISSUE TITLE
Memory Point Distribution

### ISSUE THREAD

**Issue by Sirtim94** [Lost-Outpost/thepath#17]
After leveling up to level 4 and pressing the memory function 'y'. I went to distribute perk points into the archery tree above 'Strong Bowstring' which was 2/2 in memory points already. However, I decided to interact with 'Strong Bowstring' again that was already 2/2 and the memory point went into it. I was able to continuously put memory points into the maxed out 'Strong Bowstring' an unlimited amount of times. This leads to an absurdly large number of negative memory points.
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 05 17 - 14 21 51 05](https://user-images.githubusercontent.com/105744694/168883741-203503a4-254b-455b-8f0f-be1267389bb7.png)
.

**Comment by Guitarninja2** [comment]
Are you able to do this with vanilla enderal?

**Comment by Sirtim94** [comment]
No, I checked on an old Enderal save I had.

**Comment by ArceyTheSecond** [comment]
This may have to do with the Amnesia shrine. I recall not using it because it was supposedly riddled with odd side effects. You may wanna check out the Known Issues on the Nexus page [here](https://www.nexusmods.com/enderalspecialedition/mods/6?tab=description).

**Comment by Guitarninja2** [comment]
Ah, amazing. Yes I will likely just remove that mod. Not a huge fan of it anyway.

**Comment by Keranos89** [comment]
I've observed that this negative memory point issue occurs when you use the hotkey to close the menu. If instead you first mouse over the option so that arrows appear around it and then use the hotkey or click on it, it works as its supposed to.

**Comment by Guitarninja2** [comment]
Fixed in 1.2
