### ISSUE TITLE
[1.1.0] Enderal-specific animations (still) don't play

### ISSUE THREAD

**Issue by ArceyTheSecond** [Lost-Outpost/thepath#19]
Basically a copy of  #15.

Despite our best efforts so far the animations that were introduced by Enderal still don't play (daddy munching deer etc) whenever Nemesis is in use. I tried a full wipe on the EnderalSE installation/stockgame and related folder in documents and did a full reinstall to make sure no old files were preventing a proper working.

Somehow I'm now no longer able to reproduce working animations through the previous workaround.
Will continue to do some poking around in the hopes of fixing it but the previous "fix" seems a fluke (for me).

**Comment by ArceyTheSecond** [comment]
Update time! Found a potential fix, and this may well fix #21 too.

I was playing around with Somnium and noticed that they included a few specific fixes to get Nemesis to play nice with XPMSSE and FNIS. Decided to play around and got the animations to work again! In short:

1. I installed the [Behaviors Pack](https://eddoursul.win/mods/enderal-se/) which is _very_ similar to the FNIS patch, probably better.
2. I installed [XP32 Maximum Skeleton Special Extended - Fixed Scripts](https://www.nexusmods.com/skyrimspecialedition/mods/44252)
3. I installed [XPMSSE - Nemesis - Script Fix - SE](https://www.nexusmods.com/skyrimspecialedition/mods/60363)
4. I changed the loadorder to end up with this:
![image](https://user-images.githubusercontent.com/105483909/169714104-81a7b90f-dfc4-4fdd-a385-d63566a630a8.png)
5. I emptied the The Path - Nemesis Output to make sure I got a clean output, and suddenly my output was 224 rather then 230 animations.
6. I booted Enderal, went to check in on good ol' dad, and could finally see him munching away happily again. 

Disclaimer: I am by no means an expert, and this whole XPMSSE / FNIS / Nemesis thing is giving me a headache. I also haven't done any thorough testing yet on the other animations and whether they'll now play nice (such as from the dodgemod etc).

Will do some more testing but it looks promising. I'll also do another check on executing "just" step 1 and 5 to double check necessity of steps.

**Comment by ArceyTheSecond** [comment]
Final addition: Tested dodging and that still works beautifully, even with above loadorder.

**Comment by geophyzz** [comment]
I tried to reproduce this, but got errors in Nemesis (missing cached files) and reinstalled.

**Comment by ArceyTheSecond** [comment]
> I tried to reproduce this, but got errors in Nemesis (missing cached files).

Correct. Since we wipe the output you'll have to manually set the mods that need to be included. I just wrote down which ones those were and made sure to tick them.

**Comment by geophyzz** [comment]
Thanks for the tip, but still get same errors. Seems to be Windows Virus protection was getting in the way... so I added a process exclusion for Nemesis. And it ran: 224 animations. Now to test!  Also, I should have written where FNIS.esp should be loaded but  I think is was at Priority 151.   Hope it works!!

**Comment by geophyzz** [comment]
Your solution looks like it fixed pipe smoking, which is much needed!! Some of Calia's unique animations don't work (e.g. Calia vs the Bandit lord in Deus ex machina).  I added in https://www.nexusmods.com/enderalspecialedition/mods/361?tab=description, but that didn't help Calia.  I feel we are close and hope this helps Guitarninja solve the problem.

**Comment by Guitarninja2** [comment]
Yeah thank you all a ton. When I'm finished updating my other modlist I should have time to circle back and make sure this gets resolved.

**Comment by gabrielreichelt** [comment]
> > I tried to reproduce this, but got errors in Nemesis (missing cached files).
> 
> Correct. Since we wipe the output you'll have to manually set the mods that need to be included. I just wrote down which ones those were and made sure to tick them.

@ArceyTheSecond sorry for the dumb question, but how do you even update Nemesis? Running the file in it's default location doesn't let me update it - the app just crashes. SHould it be redownloaded or placed elsewhere like the mod description suggests?

**Comment by ArceyTheSecond** [comment]
@gabrielreichelt you probably just need to enable it:
![image](https://user-images.githubusercontent.com/105483909/170934220-4c67152e-a152-4a8b-9771-cc801e641f45.png)
Enter "The Path Nemesis Output" (there should be an auto complete as soon as you start typing) into the "Create files in mod" dropdown.
You also may have to manually disable Real-Time protection from Windows Defender as mentioned [here](https://www.reddit.com/r/skyrimmods/comments/pgvwz9/psa_for_those_of_you_getting_nemesis_unlimited/) to get it running.

As @Guitarninja2 mentioned though, he's probably picking this up soonish, so might as well wait ;-)

**Comment by gabrielreichelt** [comment]
> As @Guitarninja2 mentioned though, he's probably picking this up soonish, so might as well wait ;-)

Thanks so much, I managed to get it working! I added the exclusion to Windows Defender and checked the boxes as you said, but I was running the file directly from the .exe instead of MO2. By running directly there were no bugs.
