### ISSUE TITLE
[1.1.0] Npc t-pose

### ISSUE THREAD

**Issue by d3fncftw** [Lost-Outpost/thepath#21]
Npc t-pose
Location: The False Dog

version 1.1.0

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 05 21 - 23 35 44 61](https://user-images.githubusercontent.com/105186436/169678646-673b2282-3999-4b6e-9a8c-f779dbde26c2.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 05 21 - 23 35 54 52](https://user-images.githubusercontent.com/105186436/169678648-ea2e0c61-1780-4c99-ac7f-792643d75915.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 05 21 - 23 36 07 50](https://user-images.githubusercontent.com/105186436/169678649-b07ee035-6118-4363-9051-d5f2ee371fe2.png)

**Comment by ArceyTheSecond** [comment]
May need: 
![image](https://user-images.githubusercontent.com/105483909/169709540-9e837afb-2ccc-4212-a8dd-1429566001c8.png)

From https://eddoursul.win/mods/enderal-se/
Nemesis - related with the FNIS/skeletal issue.
