### ISSUE TITLE
Unable to complete install; Unable to download Data_SKSE_Plugins_SSEDisplayTweaks.dll (GameFileSourceDownloader+State|EnderalSpecialEdition|1.5.97.0|data\skse\plugins\ssedisplaytweaks.dll)

### ISSUE THREAD

**Issue by ryanwkeith** [Lost-Outpost/thepath#28]
Seems to be an issue with downloading SSE Display Tweaks. The file successfully downloads from nexus into my wabbajack downloads folder but there's some issue with the hashing or the download. 
Placing the file manually into the wabbajack downlaod folder from nexus doesn't work.
Neither does toggling "Use Network Workaround (Slow)"

![image](https://user-images.githubusercontent.com/66140977/178789446-5f229b9c-c7dc-41ff-8902-426efefc89c9.png)

**Comment by Guitarninja2** [comment]
Fixed in 1.2
