### ISSUE TITLE
Unable to download Data_SKSE_Plugins_SSEDisplayTweaks.dll 

### ISSUE THREAD

**Issue by therock182** [Lost-Outpost/thepath#29]
This file was downloaded but i got this error.

2295,25 - Unable to download Data_SKSE_Plugins_SSEDisplayTweaks.dll (GameFileSourceDownloader+State|EnderalSpecialEdition|1.5.97.0|data\skse\plugins\ssedisplaytweaks.dll)
2295,25 - Cannot continue, was unable to download one or more archives
2295,25 - File hash check (-42) cf60f9b5731e78d5e0bf8e23785d6118d0113d740f159bed90b03eb8012d60e4

**Comment by newtown03** [comment]
I'm getting the same issue with trying to download today.

**Comment by therock182** [comment]
this is the file you need, just download and put it in the downloads folder from wabbajack.

https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=246276&game_id=1704

i found this solution on the discord server "the lost outpost" under the path - help channel.

**Comment by newtown03** [comment]
Yes! Thank you, solved!

**Comment by auroralovecraft** [comment]
Hi, I'm sorry to necro a week old, resolved, issue, but I'm having the same problem. I tried placing the download you provided in the download folder for Wabbajack, but it did not resolve the issue for me. Also, EAWO Part 2 seems to be messed up. I got this error:
Unable to hash file \EAWO Part 2-208-1-01-1627031077.7z - Data error (cyclic redundancy check)
Unable to download Data_SKSE_Plugins_SSEDisplayTweaks.dll (GameFileSourceDownloader+State | EnderalSpecialEdition | 1.5.97.0 | data\skse\plugins\ssedisplaytweaks.dll 
I've also included the log, if that helps. 
[Wabbajack.current.log](https://github.com/Lost-Outpost/thepath/files/9182257/Wabbajack.current.log)

**Comment by newtown03** [comment]
I kept putting the SKSE file in different folders and restarting the download until it finally worked, the folded that it ended up in was:

This PC>Local Disk(C:)>Wabbajack>downloaded_mod_lists 

once I had the SKSE file there it all worked, good luck

**Comment by auroralovecraft** [comment]
fixed both issues after a while, the solution if anyone else happens to see this, is to extract the SSEDisplayTweaks.dll from the link above and rename it to Data_SKSE_Plugins_SSEDisplayTweaks.dll and OVERWRITE or DELETE the one already in the download folder. its a simple version mismatch.

**Comment by Dragnier** [comment]
> 

This is the correct answer.

**Comment by shaggymonster** [comment]
Sanity Check please, I have applied the fix described and all is well.  However the DLL is a deprecated version so updating the Published Modlist with the latest version might be a better solution?

**Comment by Guitarninja2** [comment]
Fixed in 1.2
